version: '3.7'

services:
  app:
    container_name: dj_bank_app
    build: .
    command: bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/dj_bank/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure:10
  db:
    container_name: dj_bank_database
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'dj_bank'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: